### ISSUE TITLE
Fix Typo (ArXiv link)

### ISSUE THREAD

**Issue by gh-BumsooKim** [MKFMIKU/vidm#4]
I'm not sure that you intentionally set the ArXiv link to https://arxiv.org/abs/2111.09881 (**Restormer**) in README.md .
I think it have to be changed as https://arxiv.org/abs/2212.00235 (**VIDM**, paper of this repo.)

**Comment by kartheekmedathati** [comment]
Was about to write the same comment :)

**Comment by MKFMIKU** [comment]
@gh-BumsooKim @kartheekmedathati Big thanks to your reminds. (The error link let me lose so many potential citations)

**Comment by gh-BumsooKim** [comment]
Good! your welcome
